PrestaSitemapBundle_index:
    path:     "/%presta_sitemap.sitemap_file_prefix%.{_format}"
    defaults: { _controller: presta_sitemap.controller::indexAction }
    requirements:
        _format: xml

PrestaSitemapBundle_section:
    path:     "/%presta_sitemap.sitemap_file_prefix%.{name}.{_format}"
    defaults: { _controller: presta_sitemap.controller::sectionAction }
    requirements:
        _format: xml
